language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - flake8 . --ignore=F841,W503,E126,E123,E501
  - python3 -m pytest --cov=webapp --cov-report=xml
deploy:
  provider: heroku
  app: lp-bs
  api_key:
    secure: "56cc9a85-e560-40c2-af9a-df8fc12d78f3"

