language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - flake8 . --ignore=F841,W503,E126,E123
  - python3 -m pytest --cov=webapp --cov-report=xml
deploy:
  provider: heroku
  api_key:
    secure: "a8793c72-ce50-4e92-ba39-4dfbb4a1602c"
  app: books_search