language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - flake8 .
  - pytest .

deploy:
  provider: heroku
  api_key:
    secure: 0d078782-4f79-4acf-99df-36075189d72b