"""added field visit_data

Revision ID: 51739a8e9a6d
Revises: a951e96a2dcc
Create Date: 2019-11-03 13:01:19.206714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51739a8e9a6d'
down_revision = 'a951e96a2dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('count_book', sa.Column('visit_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('count_book', 'visit_data')
    # ### end Alembic commands ###
