"""removed count

Revision ID: d7cb8eece916
Revises: 51739a8e9a6d
Create Date: 2019-11-04 12:03:35.649286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cb8eece916'
down_revision = '51739a8e9a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('count_book', 'count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('count_book', sa.Column('count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
